### ISSUE TITLE
GraphCodeBert在下游任务中“my-languages.so”文件报错

### ISSUE THREAD

**Issue by huangkNIPC** [microsoft/CodeBERT#110]

**Comment by lihuiuyun** [comment]
请问你解决了吗  我也出现了报错
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/root/autodl-tmp/LineVul-main/linevul/maintest.py", line 61, in <module>
    LANGUAGE = Language('parser/my-languages.so', lang)
  File "/root/miniconda3/lib/python3.8/site-packages/tree_sitter/__init__.py", line 83, in __init__
    language_function = getattr(self.lib, "tree_sitter_%s" % name)
  File "/root/miniconda3/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/root/miniconda3/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: parser/my-languages.so: undefined symbol: tree_sitter_c

**Comment by duyali2000** [comment]
run the build.py
