### ISSUE TITLE
Type Error：when I running CodeReviewer

### ISSUE THREAD

**Issue by mao12x** [microsoft/CodeBERT#222]
This is the problem:

Traceback (most recent call last):
  File "../run_finetune_cls.py", line 268, in <module>
    main(args)
  File "../run_finetune_cls.py", line 115, in main
    config, model, tokenizer = build_or_load_gen_model(args)
  File "/data/xxx/CodeReviewer/code/models.py", line 290, in build_or_load_gen_model
    config, model, tokenizer = load_model(
  File "/data/xxx/CodeReviewer/code/models.py", line 187, in load_model
    tokenizer = tokenizer_class.from_pretrained(tokenizer_path)
  File "/home/xxx/yes/envs/review/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1777, in from_pretrained
    return cls._from_pretrained(
  File "/home/xxx/yes/envs/review/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1932, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/xxx/yes/envs/review/lib/python3.8/site-packages/transformers/models/t5/tokenization_t5.py", line 155, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/xxx/yes/envs/review/lib/python3.8/site-packages/sentencepiece/__init__.py", line 367, in Load
    return self.LoadFromFile(model_file)
  File "/home/xxx/yes/envs/review/lib/python3.8/site-packages/sentencepiece/__init__.py", line 171, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string

**Comment by Lizhmq** [comment]
Please make sure you're loading the right model. Refer to [test.model.py](https://github.com/microsoft/CodeBERT/blob/84fd94f145bdca434d92e46127f504a4605aac8f/CodeReviewer/code/test_model.py#L41) for example.

**Comment by Qinhaifu** [comment]
hi bro, when i run test_model.py, i met a error.
`Some weights of ReviewerModel were not initialized from the model checkpoint at microsoft/codereviewer and are newly initialized: ['cls_head.bias', 'cls_head.weight']`
did you meet it also? how did you deal with it
