### ISSUE TITLE
Error running inference with code search

### ISSUE THREAD

**Issue by atonkamanda** [microsoft/CodeBERT#37]
Hello, I did run the process.py and the fine tuning script, they both seemed to go well with everything executing without error, however when I want do the inference I get the following error. 

What I do 

```python
python3 run_classifier.py \
--model_type roberta \
--model_name_or_path microsoft/codebert-base \
--task_name codesearch \
--do_predict \
--output_dir ./data/codesearch/test/python \
--data_dir ./data/codesearch/test/python \
--max_seq_length 200 \
--per_gpu_train_batch_size 32 \
--per_gpu_eval_batch_size 32 \
--learning_rate 1e-5 \
--num_train_epochs 8 \
--test_file batch_0.txt \
--pred_model_dir ./models/python/checkpoint-best/ \
--test_result_dir ./results/python/0_batch_result.txt
```
What I get

```
04/24/2021 04:45:40 - WARNING - __main__ -   Process rank: -1, device: cpu, n_gpu: 0, distributed training: False, 16-bits training: False
Some weights of the model checkpoint at microsoft/codebert-base were not used when initializing RobertaForSequenceClassification: ['pooler.dense.weight', 'pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at microsoft/codebert-base and are newly initialized: ['classifier.dense.weight', 'classifier.dense.bias', 'classifier.out_proj.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
04/24/2021 04:45:49 - INFO - __main__ -   Training/evaluation parameters Namespace(adam_epsilon=1e-08, cache_dir='', config_name='', data_dir='./data/codesearch/test/python', dev_file='shared_task_dev_top10_concat.tsv', device=device(type='cpu'), do_eval=False, do_lower_case=False, do_predict=True, do_train=False, eval_all_checkpoints=False, evaluate_during_training=False, fp16=False, fp16_opt_level='O1', gradient_accumulation_steps=1, learning_rate=1e-05, local_rank=-1, logging_steps=50, max_grad_norm=1.0, max_seq_length=200, max_steps=-1, model_name_or_path='microsoft/codebert-base', model_type='roberta', n_gpu=0, no_cuda=False, num_train_epochs=8.0, output_dir='./data/codesearch/test/python', output_mode='classification', overwrite_cache=False, overwrite_output_dir=False, per_gpu_eval_batch_size=32, per_gpu_train_batch_size=32, pred_model_dir='./models/python/checkpoint-best/', save_steps=50, seed=42, server_ip='', server_port='', start_epoch=0, start_step=0, task_name='codesearch', test_file='batch_0.txt', test_result_dir='./results/python/0_batch_result.txt', tokenizer_name='', train_file='train_top10_concat.tsv', warmup_steps=0, weight_decay=0.0)
testing
404 Client Error: Not Found for url: https://huggingface.co/models/python/checkpoint-best//resolve/main/config.json
Traceback (most recent call last):
  File "/home/aton/.local/lib/python3.8/site-packages/transformers/configuration_utils.py", line 458, in get_config_dict
    resolved_config_file = cached_path(
  File "/home/aton/.local/lib/python3.8/site-packages/transformers/file_utils.py", line 1165, in cached_path
    output_path = get_from_cache(
  File "/home/aton/.local/lib/python3.8/site-packages/transformers/file_utils.py", line 1336, in get_from_cache
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/models/python/checkpoint-best//resolve/main/config.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_classifier.py", line 596, in <module>
    main()
  File "run_classifier.py", line 589, in main
    model = model_class.from_pretrained(args.pred_model_dir)
  File "/home/aton/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 975, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/aton/.local/lib/python3.8/site-packages/transformers/configuration_utils.py", line 401, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/aton/.local/lib/python3.8/site-packages/transformers/configuration_utils.py", line 478, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for './models/python/checkpoint-best/'. Make sure that:

- './models/python/checkpoint-best/' is a correct model identifier listed on 'https://huggingface.co/models'

- or './models/python/checkpoint-best/' is the correct path to a directory containing a config.json file


```

Any idea of what I could do to fix it ? Thank you very much.

**Comment by fengzhangyin** [comment]
Sorry, there was an error in the original inference  script, and  I have corrected it. 
```shell
lang=php #programming language
idx=0 #test batch idx

python run_classifier.py \
--model_type roberta \
--model_name_or_path microsoft/codebert-base \
--task_name codesearch \
--do_predict \
--output_dir ../data/codesearch/test/$lang \
--data_dir ../data/codesearch/test/$lang \
--max_seq_length 200 \
--per_gpu_train_batch_size 32 \
--per_gpu_eval_batch_size 32 \
--learning_rate 1e-5 \
--num_train_epochs 8 \
--test_file batch_${idx}.txt \
--pred_model_dir ./models/$lang/checkpoint-best/pytorch-model.bin \
--test_result_dir ./results/$lang/${idx}_batch_result.txt
```

**Comment by atonkamanda** [comment]
Thank you for your quick answer, finally I think it is a problem with the fine-tuning part,(I had nothing in my models/python directory)  I opened an another issue for more clarity, can you help me ? Here #39 I'm closing this one.
