### ISSUE TITLE
Facing issue while running “Inference and Evaluation” script of the “Code Search” project

### ISSUE THREAD

**Issue by arun05010** [microsoft/CodeBERT#9]
I am facing the below error while running “Inference and Evaluation” script of the “Code Search” project.

I am using the below machine configuration and lib version

Ubuntu 20.04
Python 3.7
torch==1.4.0
transformers==2.5.0
filelock more_itertools

09/21/2020 16:16:09 - INFO - __main__ -   Training/evaluation parameters Namespace(adam_epsilon=1e-08, cache_dir='', config_name='', data_dir='../data/codesearch/test/java', dev_file='shared_task_dev_top10_concat.tsv', device=device(type='cpu'), do_eval=False, do_lower_case=False, do_predict=True, do_train=False, eval_all_checkpoints=False, evaluate_during_training=False, fp16=False, fp16_opt_level='O1', gradient_accumulation_steps=1, learning_rate=1e-05, local_rank=-1, logging_steps=50, max_grad_norm=1.0, max_seq_length=200, max_steps=-1, model_name_or_path='microsoft/codebert-base', model_type='roberta', n_gpu=0, no_cuda=False, num_train_epochs=8.0, output_dir='../data/codesearch/test/java', output_mode='classification', overwrite_cache=False, overwrite_output_dir=False, per_gpu_eval_batch_size=32, per_gpu_train_batch_size=32, pred_model_dir='./models/java/checkpoint-best/pytorch_model.bin', save_steps=50, seed=42, server_ip='', server_port='', start_epoch=0, start_step=0, task_name='codesearch', test_file='batch_0.txt', test_result_dir='./results/java/0_batch_result.txt', tokenizer_name='', train_file='train_top10_concat.tsv', warmup_steps=0, weight_decay=0.0)
testing
Traceback (most recent call last):
  File "run_classifier.py", line 596, in <module>
    main()
  File "run_classifier.py", line 589, in main
    model = model_class.from_pretrained(args.pred_model_dir)
  File "/Users/arun/opt/anacondaDist/anaconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 383, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/Users/arun/opt/anacondaDist/anaconda3/lib/python3.8/site-packages/transformers/configuration_utils.py", line 176, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/arun/opt/anacondaDist/anaconda3/lib/python3.8/site-packages/transformers/configuration_utils.py", line 226, in get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/Users/arun/opt/anacondaDist/anaconda3/lib/python3.8/site-packages/transformers/configuration_utils.py", line 315, in _dict_from_json_file
    text = reader.read()
  File "/Users/arun/opt/anacondaDist/anaconda3/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by fengzhangyin** [comment]
Sorry, there is an error in “Inference and Evaluation” script. 
I have fixed the error.
